type Part {
    id: ID!
    name: String!
    code: String!
    type: Type!
    description: String
    revisions: [Revision!]! @hasMany
    selected_version: Version
    additional_fields: [AdditionalField]
    created_at: String!
    updated_at: String!
    creator: User
    visibleVersion: Version
}

type Revision {
    id: ID!
    revision_code: String!
    part: Part! @belongsTo
    versions: [Version!]! @hasMany
    latestVersion: Version!
    updated_at: String!
    creator: User
}

type User {
    id: ID!
    name: String!
    email: String!
}

type Type {
    id: ID!
    name: String!
}

type Version {
    id: ID!
    version_code: String!
    name: String!
    code: String!
    based_upon_version_id: Version
    basedUponVersion: Version @belongsTo(relation: "basedUpon")
    description: String
    type: Type!
    status: String
    revision: Revision! @belongsTo
    based_upon_version: Version @belongsTo(relation: "basedUponVersion")
    additional_fields: [AdditionalField!]!
        @field(
            resolver: "App\\GraphQL\\Mutations\\PartResolver@resolveAdditionalFields"
        )
    updated_at: String!
    creator: User
    enable_assembly_groups: Boolean!

    part: Part @belongsTo
}

type AdditionalField {
    id: ID!
    name: String!
    value: String
    version_id: Int!
    type_id: String
    data_type: String
    type_group: String!
    created_at: DateTime
    updated_at: DateTime

    version: Version @belongsTo
    part: Part @method(name: "part")
}

input GetVersionByVersionCodeInput {
    partId: ID!
    revisionId: ID!
    versionCode: String!
}

extend type Query {
    hello: String @field(resolver: "App\\GraphQL\\Queries\\Hello@__invoke")

    getVersion(id: ID!): Version
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getVersion")

    getVersionByVersionCode(input: GetVersionByVersionCodeInput!): Version
        @field(
            resolver: "App\\GraphQL\\Queries\\VersionQuery@getVersionByVersionCode"
        )

    getLatestVersion(partId: ID!): Version!
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getLatestVersion")

    getCustomFields(versionId: ID!): [AdditionalField!]!
        @field(resolver: "App\\GraphQL\\Queries\\VersionQuery@getCustomFields")

    types: [Type] @all

    getPartById(id: ID!): Part
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getPartById")

    parts: [Part!]
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getAllParts")

    publishedPart(groupId: ID!): [Part!]!
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getPublishedParts")

    searchParts(keyword: String!): [Part!]!
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@searchParts")

    getPartsByType(typeId: ID!): [Part!]!
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getPartsByType")
}

input CreatePartInput {
    name: String!
    code: String!
    type_id: String!
    description: String
    additional_fields: [AdditionalFieldInput!] # Các trường bổ sung theo type
    enable_assembly_groups: Boolean!
    addToGroup: Boolean = false
}

input AdditionalFieldInput {
    name: String!
    value: String
    data_type: String
    type_group: String
}

input UpdateVersionINput {
    id: ID!
    # version_code: String
    name: String!
    # code: String!
    # based_upon_version_id: ID
    # description: String
    # type_id: Int
    # additional_fields: [AdditionalFieldInput!]
    # status: String
    # enable_assembly_groups: Boolean = false
}
enum TypeGroupEnum {
    CUSTOM
    INHERITED
    STANDARD
}

enum DataTypeEnum {
    STRING
    INT
    BOOL
}

extend type Mutation {
    createPart(input: CreatePartInput!): Part
        @field(resolver: "App\\GraphQL\\Mutations\\PartResolver@createPart")

    updateVersionStatus(id: ID!): Version
        @field(
            resolver: "App\\GraphQL\\Mutations\\VersionResolver@updateVersionStatus"
        )

    createRevision(id: ID!): Revision
        @field(
            resolver: "App\\GraphQL\\Mutations\\RevisionResolver@createRevision"
        )

    updateVersion(input: UpdateVersionINput!): Version
        @field(
            resolver: "App\\GraphQL\\Mutations\\VersionResolver@updateVersion"
        )
}

type Group {
    id: ID!
    assembler_id: ID!
    name: String!
    type_id: ID
    version_id: ID
    is_optional: Boolean!

    type: Type @belongsTo
    assembler: Part @belongsTo
    version: Version @belongsTo
    groupParts: [GroupPart!] @hasMany
}

input CreateGroupInput {
    assembler_id: ID!
    name: String!
    type_id: ID
    version_id: ID
    is_optional: Boolean = false
}

type GroupPart {
    id: ID!
    group_id: ID!
    part_id: ID!
    version_id: ID!

    group: Group @belongsTo
    part: Part @belongsTo
    version: Version @belongsTo
}

extend type Query {
    groups(versionId: ID!): [Group!]
        @field(
            resolver: "App\\GraphQL\\Queries\\GroupQuery@getGroupsByVersionId"
        )
    getAdditionalFieldsFromGroup(groupId: ID!): [AdditionalField]
        @field(
            resolver: "App\\GraphQL\\Queries\\GroupQuery@getAdditionalFieldsFromGroup"
        )
}

input CreateGroupPartInput {
    group_id: ID!
    part_id: ID!
}

extend type Mutation {
    addPartToGroup(input: [CreateGroupPartInput!]): [GroupPart!]!
        @field(resolver: "App\\GraphQL\\Mutations\\GroupPartResolver@create")
}

scalar JSON @scalar(class: "MLL\\GraphQLScalars\\JSON")
scalar DateTime
    @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Codebuilder {
    id: ID!
    version_id: ID!
    name: String
    rule: String
    rule_data: JSON
    isDefault: Boolean @method(name: "isDefault")
    created_at: DateTime
    updated_at: DateTime

    version: Version @belongsTo
}

extend type Query {
    getCodeBuilderByVersion(versionId: ID!): [Codebuilder!]
        @field(
            resolver: "App\\GraphQL\\Queries\\CodeBuilderQuery@getCodeBuilderByVersion"
        )
}

extend type Mutation {
    createCodebuilder(input: CreateCodebuilderInput!): Codebuilder
        @field(
            resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@create"
        )
    updateCodebuilder(input: UpdateCodebuilderInput!): Codebuilder
        @field(
            resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@update"
        )
    deleteCodebuilder(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@delete"
        )
    # storeRuleToCodebuilder(input: StoreRuleToInput!): Codebuilder
    #     @field(
    #         resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@storeRule"
    #     )
    # addPropertyToCodebuilder(
    #     input: AddPropertyToCodebuilderInput!
    # ): Codebuilder
    #     @field(
    #         resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@addPropertyToCodebuilder"
    #     )
}

input AddPropertyToCodebuilderInput {
    id: ID!
    group_id: ID
    # field_id: ID
    field_name: String!
}

input StoreRuleToInput {
    id: ID!
    rule: String!
}

input CreateCodebuilderInput {
    version_id: ID!
    rule: String
    name: String
    is_default: Boolean = false
}

input UpdateCodebuilderInput {
    id: ID!
    rule: String
    name: String
    is_default: Boolean
}

type GeneratedCode {
    id: ID!
    generatedCode: String @method(name: "generatedCode")
}

extend type Query {
    validateGeneratedCode(codebuilderId: ID!): Boolean
        @field(resolver: "App\\GraphQL\\Queries\\GeneratedCodeQuery@validate")
    getCodeByCodebuilder(codebuilderId: ID!): [GeneratedCode!]
        @field(resolver: "App\\GraphQL\\Queries\\GeneratedCodeQuery@getCode")
}

# ----------------------------------------------------------------------------------------------

input UpdatePartInput {
    version_id: ID!
    name: String
    code: String
    description: String
    type_id: Int
    additional_fields: [AdditionalFieldInput!]
    enable_assembly_groups: Boolean
}

type EditPublishedVersionResponse {
    success: Boolean!
    message: String
}

input EditGroupInput {
    id: ID!
    name: String
    type_id: ID
    is_optional: Boolean
    version_id: ID
    assembler_id: ID
}

extend type Query {
    getVersionByCode(
        part_id: Int!
        revision_id: Int!
        version_code: String!
    ): Version
        @field(
            resolver: "App\\GraphQL\\Mutations\\VersionResolver@getVersionByCode"
        )
}

input VersionFiltersInput {
    enable_assembly_groups: Boolean
    status: String
    revision_id: ID
}
extend type Query {
    searchVersionsAssembler(filter: VersionFiltersInput): [Version!]!
        @field(
            resolver: "App\\GraphQL\\Mutations\\VersionResolver@searchVersionsAssembler"
        )
}

type Query {
    additionalFieldsByVersionId(version_id: ID!): [AdditionalField!]!
        @field(
            resolver: "App\\GraphQL\\Resolvers\\AdditionalFieldResolver@getAllVersion"
        )

    additionalField(id: ID!): AdditionalField
        @field(
            resolver: "App\\GraphQL\\Resolvers\\AdditionalFieldResolver@getVersionById"
        )

    getParts(published: Boolean!): [Part!]!
        @field(
            resolver: "App\\GraphQL\\Queries\\PartQuery@getPartsByPublishedStatus"
        )
}

input PartFilterInput {
    keyword: String
    type_id: ID
    published: Boolean
    is_assembler: Boolean
}

extend type Query {
    filterParts(filter: PartFilterInput): [Part!]!
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@filterParts")
}

extend type Mutation {
    updatePart(input: UpdatePartInput!): Version
        @field(resolver: "App\\GraphQL\\Mutations\\PartResolver@updatePart")

    deleteDraftVersion(version_id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Mutations\\PartResolver@deleteDraftVersion"
        )

    clonePublishedVersion(version_id: ID!): EditPublishedVersionResponse
        @field(
            resolver: "App\\GraphQL\\Mutations\\PartResolver@clonePublishedVersion"
        )

    deletePart(id: ID!): Boolean
        @field(resolver: "App\\GraphQL\\Mutations\\PartResolver@deletePart")

    deleteGroup(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Mutations\\GroupPartResolver@deleteGroup"
        )
    deleteGroupPartById(id: Int!): Boolean
        @field(resolver: "GroupPartResolver@deleteGroupPartById")

    updateGroup(input: EditGroupInput!): Group!
        @field(
            resolver: "App\\GraphQL\\Mutations\\GroupResolver@updateGroupById"
        )
    createGroup(input: CreateGroupInput!): Group
        @field(resolver: "App\\GraphQL\\Mutations\\GroupResolver@createGroup")

    # duplicateFullPart(part_id: ID!, code: String!): Part
    #     @field(
    #         resolver: "App\\GraphQL\\Mutations\\PartResolver@duplicateFullPart"
    #     )
}
