type Part {
    id: ID!
    name: String!
    code: String!
    type: Type!
    description: String
    revisions: [Revision!]! @hasMany
    selected_version: Version
    additional_fields: [AdditionalField]
    created_at: String!
    updated_at: String!
    creator: User
    visibleVersion: Version
}

type Revision {
    id: ID!
    revision_code: String!
    part: Part! @belongsTo
    versions: [Version!]! @hasMany
    latestVersion: Version!
    updated_at: String!
    creator: User
}

type User {
    id: ID!
    name: String!
    email: String!
}

type Type {
    id: ID!
    name: String!
}

type Version {
    id: ID!
    version_code: String!
    name: String!
    code: String!
    based_upon_version_id: Version
    basedUponVersion: Version @belongsTo(relation: "basedUpon")
    description: String
    type: Type!
    status: String
    revision: Revision! @belongsTo
    based_upon_version: Version @belongsTo(relation: "basedUponVersion")
    additional_fields: [AdditionalField!]!
        @field(
            resolver: "App\\GraphQL\\Mutations\\PartResolver@resolveAdditionalFields"
        )
    updated_at: String!
    creator: User
    enable_assembly_groups: Boolean!
}

type AdditionalField {
    id: ID!
    name: String!
    value: String
    version_id: INT!
    type_id: String
    data_type: String
    type_group: String!
    created_at: DateTime
    updated_at: DateTime
}

extend type Query {
    hello: String @field(resolver: "App\\GraphQL\\Queries\\Hello@__invoke")

    getVersion(id: ID!): Version
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getVersion")
    getLatestVersion(partId: ID!): Version!
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getLatestVersion")

    types: [Type] @all

    getPartById(id: ID!): Part
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getPartById")
    parts: [Part!]
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getAllParts")
    publishedPart: [Part!]!
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getPublishedParts")
}

input CreatePartInput {
    name: String!
    code: String!
    type_id: String!
    description: String
    additional_fields: [AdditionalFieldInput!] # Các trường bổ sung theo type
    enable_assembly_groups: Boolean!
}

input AdditionalFieldInput {
    name: String!
    value: String!
    data_type: DataTypeEnum = STRING
}

enum TypeGroupEnum {
    CUSTOM
    INHERITED
}

enum DataTypeEnum {
    STRING
    INT
    BOOL
}

extend type Mutation {
    createPart(input: CreatePartInput!): Part
        @field(resolver: "App\\GraphQL\\Mutations\\PartResolver@createPart")

    updateVersionStatus(id: ID!): Version
        @field(
            resolver: "App\\GraphQL\\Mutations\\VersionResolver@updateVersionStatus"
        )

    createRevision(id: ID!): Revision
        @field(
            resolver: "App\\GraphQL\\Mutations\\RevisionResolver@createRevision"
        )
}

type Group {
    id: ID!
    assembler_id: ID!
    name: String!
    version_id: ID
    is_optional: Boolean

    assembler: Part @belongsTo
    version: Version @belongsTo
    groupParts: [GroupPart!] @hasMany
}

type GroupPart {
    id: ID!
    group_id: ID!
    part_id: ID!
    version_id: ID!

    group: Group @belongsTo
    part: Part @belongsTo
}

extend type Query {
    groups(versionId: ID!): [Group!]
        @field(
            resolver: "App\\GraphQL\\Queries\\GroupQuery@getGroupsByVersionId"
        )
}

input CreateGroupPartInput {
    group_id: ID!
    part_id: ID!
}

extend type Mutation {
    addPartToGroup(input: [CreateGroupPartInput!]): [GroupPart!]!
        @field(resolver: "App\\GraphQL\\Mutations\\GroupPartResolver@create")
}

# ----------------------------------------------------------------------------------------------

scalar JSON @scalar(class: "MLL\\GraphQLScalars\\JSON")

type CodebuilderRule {
    id: ID!
    version_id: ID!
    rule: JSON!
    created_at: DateTime
    updated_at: DateTime

    version: Version @belongsTo
}

extend type Query {
    codebuilderRules: [CodebuilderRule!]! @all
    codebuilderRule(id: ID!): CodebuilderRule @find
}

extend type Mutation {
    createCodebuilderRule(input: CreateCodebuilderRuleInput!): CodebuilderRule
        @field(
            resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@create"
        )

    updateCodebuilderRule(
        id: ID!
        input: UpdateCodebuilderRuleInput!
    ): CodebuilderRule
        @field(
            resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@update"
        )

    deleteCodebuilderRule(id: ID!): Boolean
        @delete(model: "App\\Models\\CodebuilderRule")
}

input CreateCodebuilderRuleInput {
    version_id: ID! @rules(apply: ["required", "exists:versions,id"])
    rule: JSON! @rules(apply: ["required", "array"])
}

input UpdateCodebuilderRuleInput {
    rule: JSON! @rules(apply: ["required", "array"])
}

input UpdatePartInput {
    version_id: ID!
    name: String
    code: String
    description: String
    type_id: Int
    additional_fields: [AdditionalFieldInput!]
}

input AdditionalFieldInput {
    name: String!
    value: String
    data_type: String
    type_group: String
}

extend type Mutation {
    updatePart(input: UpdatePartInput!): Version
        @field(resolver: "App\\GraphQL\\Mutations\\PartResolver@updatePart")

    deleteDraftVersion(version_id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Mutations\\PartResolver@deleteDraftVersion"
        )

    editPublishedVersion(version_id: ID!): Version
        @field(
            resolver: "App\\GraphQL\\Mutations\\PartResolver@editPublishedVersion"
        )
}
