type Part {
    id: ID!
    name: String!
    code: String!
    type: Type!
    description: String
    revisions: [Revision!]! @hasMany
    selected_version: Version
    additional_fields: [AdditionalField]
    created_at: String!
    updated_at: String!
    creator: User!
}

type Revision {
    id: ID!
    revision_code: String!
    part: Part! @belongsTo
    versions: [Version!]! @hasMany
    latest_version: String!
    updated_at: String!
    creator: User!
}

type User {
    id: ID!
    name: String!
    email: String!
}

type Type {
    id: ID!
    name: String!
}

type Version {
    id: ID!
    version_code: String!
    name: String!
    code: String!
    based_upon_version_id: Version
    description: String
    type: Type!
    status: String
    revision: Revision! @belongsTo
    additional_fields: [AdditionalField!]!
        @field(
            resolver: "App\\GraphQL\\Mutations\\PartResolver@resolveAdditionalFields"
        )
    updated_at: String!
    creator: User!
}

type AdditionalField {
    id: ID!
    name: String!
    value: String
    type_id: ID
    data_type: String
    created_at: DateTime
    updated_at: DateTime
}

extend type Query {
    hello: String @field(resolver: "App\\GraphQL\\Queries\\Hello@__invoke")
    getVersion(partId: ID!, revisionId: ID!, versionCode: String!): Version
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getVersion")

    types: [Type] @all

    getPartById(id: ID!): Part
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getPartById")
    parts: [Part!]
        @field(resolver: "App\\GraphQL\\Queries\\PartQuery@getAllParts")
}

input CreatePartInput {
    name: String!
    code: String!
    type_id: String!
    description: String
    additional_fields: [AdditionalFieldInput!] # Các trường bổ sung theo type
    enable_assembly_groups: Boolean!
}

input AdditionalFieldInput {
    name: String!
    value: String!
    data_type: DataTypeEnum = STRING
}

enum DataTypeEnum {
    STRING
    INT
    BOOL
}

extend type Mutation {
    createPart(input: CreatePartInput!): Part
        @field(resolver: "App\\GraphQL\\Mutations\\PartResolver@createPart")
}

# ----------------------------------------------------------------------------------------------

type GroupPart {
    id: ID!
    group_id: ID!
    part_id: ID!
    quantity: Int!
    group: Group @belongsTo
    part: Part @belongsTo
    created_at: DateTime
    updated_at: DateTime
}

type Query {
    groupParts: [GroupPart!]! @all
    groupPart(id: ID!): GroupPart @find
}

type Mutation {
    createGroupPart(input: CreateGroupPartInput!): GroupPart
        @field(resolver: "App\\GraphQL\\Mutations\\GroupPartResolver@create")

    updateGroupPart(id: ID!, input: UpdateGroupPartInput!): GroupPart
        @update(model: "App\\Models\\GroupPart")

    deleteGroupPart(id: ID!): Boolean @delete(model: "App\\Models\\GroupPart")
}

input CreateGroupPartInput {
    group_id: ID! @rules(apply: ["required", "exists:groups,id"])
    part_id: ID! @rules(apply: ["required", "exists:parts,id"])
    quantity: Int! @rules(apply: ["required", "integer", "min:1"])
}

input UpdateGroupPartInput {
    quantity: Int! @rules(apply: ["required", "integer", "min:1"])
}

type Group {
    id: ID!
    assembler_id: ID!
    name: String!
    version_id: ID
    is_optional: Boolean
    created_at: DateTime
    updated_at: DateTime

    assembler: Part @belongsTo
    version: Version @belongsTo
    groupParts: [GroupPart!]! @hasMany
}

extend type Query {
    groups: [Group!]! @all
    group(id: ID!): Group @find
}

extend type Mutation {
    createGroup(input: CreateGroupInput!): Group
        @create(model: "App\\Models\\Group")

    updateGroup(id: ID!, input: UpdateGroupInput!): Group
        @update(model: "App\\Models\\Group")

    deleteGroup(id: ID!): Boolean @delete(model: "App\\Models\\Group")
}

input CreateGroupInput {
    assembler_id: ID! @rules(apply: ["required", "exists:parts,id"])
    name: String! @rules(apply: ["required", "string", "max:100"])
    version_id: ID @rules(apply: ["nullable", "exists:versions,id"])
    is_optional: Boolean
}

input UpdateGroupInput {
    name: String @rules(apply: ["string", "max:100"])
    is_optional: Boolean
}

scalar JSON @scalar(class: "MLL\\GraphQLScalars\\JSON")

type CodebuilderRule {
    id: ID!
    version_id: ID!
    rule: JSON!
    created_at: DateTime
    updated_at: DateTime

    version: Version @belongsTo
}

extend type Query {
    codebuilderRules: [CodebuilderRule!]! @all
    codebuilderRule(id: ID!): CodebuilderRule @find
}

extend type Mutation {
    createCodebuilderRule(input: CreateCodebuilderRuleInput!): CodebuilderRule
        @field(
            resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@create"
        )

    updateCodebuilderRule(
        id: ID!
        input: UpdateCodebuilderRuleInput!
    ): CodebuilderRule
        @field(
            resolver: "App\\GraphQL\\Mutations\\CodebuilderRuleResolver@update"
        )

    deleteCodebuilderRule(id: ID!): Boolean
        @delete(model: "App\\Models\\CodebuilderRule")
}

input CreateCodebuilderRuleInput {
    version_id: ID! @rules(apply: ["required", "exists:versions,id"])
    rule: JSON! @rules(apply: ["required", "array"])
}

input UpdateCodebuilderRuleInput {
    rule: JSON! @rules(apply: ["required", "array"])
}

input EditPartInput {
    id: ID!
    name: String
    code: String
    description: String
    type_id: Int
    additional_fields: [AdditionalFieldInput!]
}

input AdditionalFieldInput {
    name: String!
    value: String
    data_type: String
}

extend type Mutation {
    editPart(input: EditPartInput!): Version
        @field(resolver: "App\\GraphQL\\Mutations\\PartResolver@editPart")
}
